version: '3.9'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - userdata:/root

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: 'techfreaks'
      MYSQL_PASS: 'techfreaks'
    volumes:
      - my-datavolume:/var/lib/mysql

  techfreaks:
    build: "techfreaks/."
    restart: always
    ports:
      - 80:80
    volumes:
      - userdata:/root

volumes:
  userdata:
  my-datavolume: